---
# tasks file for lb_role
#
- package:
        name: "haproxy"
        state: present

- template:
        src: "haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"

- service:
        name: "haproxy"
        state: restarted
        enabled: yes
- firewalld:
        immediate: yes
        permanent: yes
        port: 8080/tcp
        state: enabled
